name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: stoppenkast

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t lazynews .

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Stop & remove old container (ignore errors)
        run: |
          docker stop lazynews || true
          docker rm lazynews || true
  
      - name: Run new container
        run: |
          docker run -d --name lazynews -p 3000:3000 lazynews:latest
