name: Docker CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t lazynews:latest .

      - name: Stop & remove old container
        run: |
          docker stop lazynews || true
          docker rm lazynews || true

      - name: Run new container
        run: docker run -d --name lazynews -p 3000:3000 lazynews:latest
